# Generated by Django 5.2.5 on 2025-08-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admindata',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('contact', models.TextField(max_length=100)),
            ],
        ),
    ]
