# Generated by Django 5.2.4 on 2025-08-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='logindata',
        ),
    ]
