# Generated by Django 5.2.4 on 2025-08-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_login_logindata'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentdata',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('contact', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('phone', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('gender', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=100)),
            ],
        ),
    ]
