# Generated by Django 5.2.4 on 2025-08-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_studentdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logindata',
            name='id',
        ),
        migrations.AlterField(
            model_name='logindata',
            name='email',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
