# Generated by Django 5.2.4 on 2025-08-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_logindata_id_alter_logindata_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='password',
        ),
    ]
