# Generated by Django 5.2.4 on 2025-08-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_studentdata_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
