# Generated by Django 5.2.4 on 2025-08-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_coursedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedata',
            name='id',
        ),
        migrations.AlterField(
            model_name='coursedata',
            name='coursename',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
