# Generated by Django 5.2.4 on 2025-08-28 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_coursedata_id_alter_coursedata_coursename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coursedata',
        ),
    ]
