# Generated by Django 5.2.4 on 2025-08-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_coursedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursedata',
            fields=[
                ('course_id', models.CharField(auto_created=True, max_length=100, primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
