# Generated by Django 5.2.4 on 2025-08-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_coursedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedata',
            name='course_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
