# Generated by Django 5.2.4 on 2025-08-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_coursedata_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedata',
            name='course_id',
            field=models.IntegerField(auto_created=0, primary_key=True, serialize=False),
        ),
    ]
