# Generated by Django 5.2.4 on 2025-08-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_coursedata_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='paydata',
            fields=[
                ('course_id', models.IntegerField(auto_created=0)),
                ('student_email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('utr', models.CharField(max_length=100)),
            ],
        ),
    ]
