# Generated by Django 5.2.4 on 2025-08-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_paydata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='paydata',
        ),
    ]
