# Generated by Django 5.2.4 on 2025-08-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_paydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='paydata',
            fields=[
                ('course_id', models.IntegerField()),
                ('student_email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('utr', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
