# Generated by Django 5.2.4 on 2025-08-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_paydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='paydata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paydata',
            name='student_email',
            field=models.EmailField(max_length=100),
        ),
    ]
