# Generated by Django 5.2.4 on 2025-08-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_paydata_id_alter_paydata_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paydata',
            name='id',
        ),
        migrations.AlterField(
            model_name='paydata',
            name='course_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
