# Generated by Django 5.2.4 on 2025-08-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_paydata_id_alter_paydata_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paydata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paydata',
            name='course_id',
            field=models.IntegerField(),
        ),
    ]
