# Generated by Django 5.2.4 on 2025-08-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_paydata_id_alter_paydata_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paydata',
            name='id',
            field=models.IntegerField(auto_created=0, primary_key=True, serialize=False),
        ),
    ]
