# Generated by Django 5.2.4 on 2025-08-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_coursedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursedata',
            fields=[
                ('course_id', models.IntegerField(auto_created=0, primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
