# Generated by Django 5.2.4 on 2025-08-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_coursedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='videodata',
            fields=[
                ('id', models.IntegerField(auto_created=0, primary_key=True, serialize=False)),
                ('course_id', models.IntegerField()),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
