# Generated by Django 5.2.4 on 2025-08-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_videodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='thum',
            field=models.FileField(default='no_image.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
