# Generated by Django 5.2.4 on 2025-08-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_videodata_thum'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodata',
            name='topic',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
