# Generated by Django 5.2.4 on 2025-08-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_videodata_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedata',
            name='pic',
            field=models.FileField(default='second', upload_to='images/'),
            preserve_default=False,
        ),
    ]
