# Generated by Django 5.2.4 on 2025-08-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_coursedata_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentreveivedata',
            fields=[
                ('id', models.IntegerField(auto_created=0, primary_key=True, serialize=False)),
                ('qr', models.FileField(upload_to='qr/')),
            ],
        ),
    ]
