# Generated by Django 5.2.4 on 2025-08-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_paymentreveivedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='upidata',
            fields=[
                ('upi', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('upi_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='paymentreveivedata',
        ),
    ]
