# Generated by Django 5.2.4 on 2025-08-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_upidata_delete_paymentreveivedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='upidata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='upidata',
            name='upi',
            field=models.CharField(max_length=100),
        ),
    ]
