# Generated by Django 5.2.4 on 2025-08-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_upidata_id_alter_upidata_upi'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedata',
            name='details',
            field=models.TextField(default='ddd'),
            preserve_default=False,
        ),
    ]
