# Generated by Django 5.2.4 on 2025-08-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_coursedata_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='notesdata',
            fields=[
                ('id', models.IntegerField(auto_created=0, primary_key=True, serialize=False)),
                ('course_id', models.IntegerField()),
                ('note_file', models.FileField(upload_to='notes/')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
