# Generated by Django 5.2.4 on 2025-08-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_notesdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='paydata',
            name='course_name',
            field=models.CharField(default='dd', max_length=100),
            preserve_default=False,
        ),
    ]
