# Generated by Django 5.2.4 on 2025-08-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_paydata_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paydata',
            name='dates',
            field=models.DateField(default='2025-09-01'),
            preserve_default=False,
        ),
    ]
