# Generated by Django 5.2.4 on 2025-08-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_paydata_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paydata',
            name='dates',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
